### ISSUE TITLE
Not saving workflow.

### ISSUE THREAD

**Issue by fogostudio** [palant/extended-saveimage-comfyui#2] opened 2023-11-21 02:24 UTC
For me it's not saving the workflow for neither jpg nor webp.

**Comment by palant** [comment] 2023-11-21 07:59
How do you know that the workflow isn’t being saved rather than not being restored from these images?

**Comment by palant** [comment] 2023-11-23 08:05
Closing as I cannot reproduce this issue. Maybe if you provide me with some additional details.

**Comment by fogostudio** [comment] 2023-11-23 15:09
That's an interesting question. If the information is indeed being saved but not reusable in ComfyUI (drag and drop the image to open the workflow) , then for me it would be the same as not having it at all.

**Comment by palant** [comment] 2023-11-23 17:12
Interesting, this image has no embedded metadata. Do you by any chance pass `--disable_metadata` parameter to ComfyUI? I think that’s the only scenario where an image would be saved but without any metadata. Assuming that you aren’t using some other node rather than this one here.

**Comment by fogostudio** [comment] 2023-11-23 17:38
Hello,

I don't use the  `--disable_metadata` parameter, I'm only using these:
`.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto 
`
Here's a screenshot of the workflow:

![Untitled](https://github.com/palant/extended-saveimage-comfyui/assets/47007002/c1d35752-6b2c-428c-9107-45a4f1ca5b28)

**Comment by fogostudio** [comment] 2023-11-23 17:40
Here's a normal PNG with the embedded workflow:
![ComfyUI_00346_](https://github.com/palant/extended-saveimage-comfyui/assets/47007002/4912660d-3906-4525-96a2-ed5f66f15161)

**Comment by palant** [comment] 2023-11-23 21:33
The node provided by this extension is called “Save Image (Extended)”. I’m not quite sure which custom node you’ve got but you are definitely in the wrong repository.

**Comment by fogostudio** [comment] 2023-11-23 22:18
Apologies for the confusion, here's the correct screenshot and workflow:

Screenshot for Save Image (Extended)
![screenshot](https://github.com/palant/extended-saveimage-comfyui/assets/47007002/736b6089-9c16-4a48-bf38-5261a7980a42)

Workflow:
![ComfyUI_00349_](https://github.com/palant/extended-saveimage-comfyui/assets/47007002/44e02d22-9cde-4bcd-8809-af77271cf596)

**Comment by fogostudio** [comment] 2023-11-23 22:20
And here's the exported image using your extension:

![ComfyUI_00348_](https://github.com/palant/extended-saveimage-comfyui/assets/47007002/f9439696-943d-4a32-b5cf-40670fc047ef)

**Comment by palant** [comment] 2023-11-24 06:35
This image does include the workflow. So presumably it won’t load? There is most likely a JavaScript error then.

After you attempt to load the image, press F12 to open Developer Tools. You might also need to switch to the Console tab. If you have an error message there, please copy it here.

**Comment by fogostudio** [comment] 2023-11-24 14:08
Yeah, it doesn't load, here's the console log:

workflowImage.js:399 Uncaught (in promise) ReferenceError: resolve is not defined
    at reader.onload (workflowImage.js:399:10)
reader.onload @ workflowImage.js:399
load (async)
(anonymous) @ workflowImage.js:393
app.handleFile @ workflowImage.js:389
(anonymous) @ app.js:732

**Comment by palant** [comment] 2023-11-24 14:16
`workflowImage.js` isn’t my file, and neither something from the core application. Looks like this is a conflict with some other extension. Can you figure out which one it belongs to?

**Comment by fogostudio** [comment] 2023-11-24 14:24
You are correct, it belongs to 'ComfyUI-Custom-Scripts' , I disabled that extension and now yours is working correctly.

**Comment by palant** [comment] 2023-11-24 15:38
Yes, that’s a bug in ComfyUI-Custom-Scripts, here: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/27555d4f71bb4e24b87571f89eab2b4a06677bb6/web/js/workflowImage.js#L392-L403

This function is calling `resolve()` on three occasions when it should have called `r()`. This makes it error out before it can call the original `handleFile()` function, so the code here never gets a chance to run. In fact, this completely breaks the handling of JPEG files.

**Closed by palant** 2023-11-24 15:38 UTC
Labels: invalid

**Comment by fogostudio** [comment] 2023-11-24 17:42
Yes, I will disable the other extension since it seems to be causing problems as you mentioned. Thanks again for your support!
